POST http://localhost:3000/message HTTP/1.1
content-type: application/json

{
	"message": "first message"
}

###

GET http://localhost:3000/message HTTP/1.1

###

GET http://localhost:3000/message/616b0cd1f504f019052815f8 HTTP/1.1

###

PUT http://localhost:3000/message/616b0cd1f504f019052815f8 HTTP/1.1
content-type: application/json

{
	"message": "first updated message"
}

###

DELETE http://localhost:3000/message/616b0cd1f504f019052815f8 HTTP/1.1
